const menus = [
  {name:'얼큰 순두부찌개',category:'한식',emoji:'🍲',price:'₩9,000',time:'15분',mood:'든든하게'}, {name:'제육볶음',category:'한식',emoji:'🥘',price:'₩10,000',time:'20분',mood:'매콤하게'}, {name:'김치찌개',category:'한식',emoji:'🍲',price:'₩8,000',time:'15분',mood:'든든하게'}, {name:'된장찌개',category:'한식',emoji:'🍚',price:'₩8,000',time:'15분',mood:'가볍게'}, {name:'불고기 백반',category:'한식',emoji:'🥩',price:'₩12,000',time:'25분',mood:'든든하게'}, {name:'비빔밥',category:'한식',emoji:'🍳',price:'₩9,000',time:'15분',mood:'가볍게'}, {name:'닭갈비',category:'한식',emoji:'🍗',price:'₩12,000',time:'25분',mood:'매콤하게'}, {name:'보쌈 정식',category:'한식',emoji:'🥬',price:'₩13,000',time:'25분',mood:'든든하게'}, {name:'감자탕',category:'한식',emoji:'🍖',price:'₩11,000',time:'20분',mood:'든든하게'}, {name:'냉면',category:'한식',emoji:'🍜',price:'₩10,000',time:'15분',mood:'가볍게'},
  {name:'연어 초밥',category:'일식',emoji:'🍣',price:'₩14,000',time:'15분',mood:'가볍게'}, {name:'돈카츠',category:'일식',emoji:'🍱',price:'₩11,000',time:'20분',mood:'든든하게'}, {name:'규동',category:'일식',emoji:'🍛',price:'₩9,000',time:'15분',mood:'든든하게'}, {name:'가츠동',category:'일식',emoji:'🍳',price:'₩10,000',time:'15분',mood:'든든하게'}, {name:'사케동',category:'일식',emoji:'🐟',price:'₩13,000',time:'15분',mood:'가볍게'}, {name:'우동',category:'일식',emoji:'🍜',price:'₩8,000',time:'15분',mood:'가볍게'}, {name:'모밀 정식',category:'일식',emoji:'🥢',price:'₩9,000',time:'15분',mood:'가볍게'}, {name:'텐동',category:'일식',emoji:'🍤',price:'₩12,000',time:'20분',mood:'새로운 것'},
  {name:'짜장면',category:'중식',emoji:'🍜',price:'₩7,000',time:'15분',mood:'든든하게'}, {name:'짬뽕',category:'중식',emoji:'🍜',price:'₩9,000',time:'15분',mood:'매콤하게'}, {name:'탕수육',category:'중식',emoji:'🥡',price:'₩12,000',time:'20분',mood:'든든하게'}, {name:'마파두부 덮밥',category:'중식',emoji:'🍛',price:'₩9,000',time:'15분',mood:'매콤하게'}, {name:'볶음밥',category:'중식',emoji:'🍳',price:'₩8,000',time:'15분',mood:'든든하게'}, {name:'마라탕',category:'중식',emoji:'🌶️',price:'₩12,000',time:'20분',mood:'매콤하게'}, {name:'딤섬 세트',category:'중식',emoji:'🥟',price:'₩13,000',time:'20분',mood:'새로운 것'},
  {name:'떡볶이 세트',category:'분식',emoji:'🍢',price:'₩8,000',time:'15분',mood:'매콤하게'}, {name:'김밥 한 줄',category:'분식',emoji:'🍙',price:'₩4,500',time:'10분',mood:'가볍게'}, {name:'라볶이',category:'분식',emoji:'🍜',price:'₩7,000',time:'15분',mood:'매콤하게'}, {name:'돈까스 김밥',category:'분식',emoji:'🍙',price:'₩6,000',time:'10분',mood:'든든하게'}, {name:'치즈 핫도그',category:'분식',emoji:'🌭',price:'₩5,000',time:'10분',mood:'새로운 것'}, {name:'순대국',category:'분식',emoji:'🍲',price:'₩9,000',time:'15분',mood:'든든하게'},
  {name:'치킨 샐러드 랩',category:'샐러드',emoji:'🌯',price:'₩8,500',time:'10분',mood:'가볍게'}, {name:'연어 포케',category:'샐러드',emoji:'🥗',price:'₩13,000',time:'15분',mood:'가볍게'}, {name:'닭가슴살 샐러드',category:'샐러드',emoji:'🥗',price:'₩9,500',time:'10분',mood:'가볍게'}, {name:'두부 포케',category:'샐러드',emoji:'🥑',price:'₩10,000',time:'15분',mood:'가볍게'}, {name:'콥 샐러드',category:'샐러드',emoji:'🥚',price:'₩11,000',time:'15분',mood:'가볍게'}, {name:'그릭요거트 볼',category:'샐러드',emoji:'🫐',price:'₩8,000',time:'10분',mood:'가볍게'},
  {name:'토마토 파스타',category:'양식',emoji:'🍝',price:'₩12,000',time:'20분',mood:'든든하게'}, {name:'알리오 올리오',category:'양식',emoji:'🍝',price:'₩11,000',time:'20분',mood:'가볍게'}, {name:'치킨 스테이크',category:'양식',emoji:'🍗',price:'₩15,000',time:'25분',mood:'든든하게'}, {name:'버섯 크림 리조또',category:'양식',emoji:'🍚',price:'₩13,000',time:'25분',mood:'새로운 것'}, {name:'치즈 버거',category:'양식',emoji:'🍔',price:'₩10,000',time:'15분',mood:'든든하게'}, {name:'마르게리타 피자',category:'양식',emoji:'🍕',price:'₩14,000',time:'25분',mood:'새로운 것'}, {name:'오므라이스',category:'양식',emoji:'🍳',price:'₩10,000',time:'20분',mood:'든든하게'},
  {name:'소고기 쌀국수',category:'아시안',emoji:'🍜',price:'₩11,000',time:'15분',mood:'든든하게'}, {name:'탄탄멘',category:'아시안',emoji:'🍜',price:'₩12,000',time:'20분',mood:'매콤하게'}, {name:'팟타이',category:'아시안',emoji:'🍤',price:'₩12,000',time:'20분',mood:'새로운 것'}, {name:'나시고랭',category:'아시안',emoji:'🍛',price:'₩11,000',time:'20분',mood:'매콤하게'}, {name:'치킨 커리',category:'아시안',emoji:'🍛',price:'₩12,000',time:'20분',mood:'든든하게'}, {name:'반미 샌드위치',category:'아시안',emoji:'🥖',price:'₩9,000',time:'10분',mood:'가볍게'}
];

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const categories = ['전체', ...new Set(menus.map(m => m.category))];
const selected = {mood:'전체', budget:'전체', time:'전체'};
let category = '전체', current = menus[0], history = JSON.parse(localStorage.getItem('lunch-history') || '[]');
const userId = localStorage.getItem('lunch-user-id') || crypto.randomUUID();
localStorage.setItem('lunch-user-id', userId);
const config = window.SUPABASE_CONFIG || {};
const dbEnabled = config.url && !config.url.includes('YOUR_PROJECT') && config.anonKey && !config.anonKey.includes('YOUR_');

function today(){ return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date()); }
function filtered(){ return menus.filter(m => { const price=Number(m.price.replace(/\D/g,'')); const quick=Number(m.time.replace(/\D/g,''))<=15; return (category === '전체' || m.category === category) && (selected.mood === '전체' || m.mood === selected.mood) && (selected.budget === '전체' || (selected.budget === '1만원 이하' ? price <= 10000 : price > 10000)) && (selected.time === '전체' || (selected.time === '15분 이내' ? quick : !quick)); }); }
function renderCategories(){ $('#categoryTabs').innerHTML = categories.map(c => `<button class="category-tab ${c===category?'active':''}" data-category="${c}">${c}</button>`).join(''); $('#menuCount').textContent = `${filtered().length}개`; }
function show(m){ current=m; $('#resultMood').textContent=m.mood==='새로운 것'?'새로운':m.mood.replace('하게','한'); $('#resultName').textContent=m.name; $('#resultDesc').textContent=`${m.category} 메뉴로 즐기는 ${m.mood} 점심. 오늘의 기분에 잘 어울리는 한 끼예요.`; $('#resultPrice').textContent=m.price; $('#resultTime').textContent=`◷ ${m.time} 내외`; $('#resultType').textContent=m.category; $('.food-emoji').textContent=m.emoji; }
function renderCards(){ const list=filtered(); $('#menuGrid').innerHTML=list.map(m=>{ const picked=history.some(h=>(h.name||h.menu_name)===m.name&&(h.eaten_on||h.date)===today()); return `<article class="menu-card" data-name="${m.name}"><div class="card-art">${m.emoji}</div><div class="card-copy"><span class="category-label">${m.category}</span><h3>${m.name}</h3><p>${m.mood} · ${m.time} 내외</p><div class="card-meta"><span>${m.price}</span><span>점심 메뉴</span></div><button class="pick-btn ${picked?'picked':''}" data-pick="${m.name}">${picked?'기록했어요':"Today's Pick"}</button></div></article>`; }).join(''); $('#menuCount').textContent=`${list.length}개`; }
function renderHistory(){ $('#historyList').innerHTML=history.length ? history.map(h=>`<div class="history-item"><span>${h.emoji||'🍽️'}</span><b>${h.name||h.menu_name}</b><em>${h.eaten_on||h.date||today()}</em><small>${h.category||''}</small></div>`).join('') : '<p class="empty">아직 기록이 없어요. 메뉴 카드에서 오늘 먹은 메뉴를 기록해보세요!</p>'; }
async function loadHistory(){ if(!dbEnabled) return; try{ const res=await fetch(`${config.url}/rest/v1/lunch_history?user_id=eq.${encodeURIComponent(userId)}&order=eaten_on.desc,created_at.desc&limit=20`,{headers:{apikey:config.anonKey,Authorization:`Bearer ${config.anonKey}`}}); if(res.ok){ history=await res.json(); renderHistory(); } }catch(e){ console.warn('Supabase 기록을 불러오지 못했습니다.',e); } }
async function pick(m){ const date=today(); if(history.some(h=>(h.name||h.menu_name)===m.name&&(h.eaten_on||h.date)===date)) return; const record={name:m.name,category:m.category,emoji:m.emoji,eaten_on:date,date}; history.unshift(record); history=history.slice(0,20); localStorage.setItem('lunch-history',JSON.stringify(history)); renderHistory(); renderCards(); if(dbEnabled){ try{ const res=await fetch(`${config.url}/rest/v1/lunch_history`,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${config.anonKey}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({user_id:userId,menu_name:m.name,category:m.category,eaten_on:date})}); if(!res.ok) throw new Error(await res.text()); }catch(e){ console.warn('Supabase 저장 실패. 브라우저 기록은 유지됩니다.',e); } } }
function recommend(){ const list=filtered(); show(list[Math.floor(Math.random()*list.length)]||menus[0]); $('#result').scrollIntoView({behavior:'smooth',block:'start'}); }

$$('.chip').forEach(btn=>btn.addEventListener('click',()=>{ const g=btn.dataset.group; selected[g]=btn.dataset.value; $$(`[data-group="${g}"]`).forEach(b=>b.classList.remove('selected')); btn.classList.add('selected'); renderCards(); }));
$('#categoryTabs').addEventListener('click',e=>{ const btn=e.target.closest('[data-category]'); if(!btn)return; category=btn.dataset.category; renderCategories(); renderCards(); });
$('#menuGrid').addEventListener('click',e=>{ const pickBtn=e.target.closest('[data-pick]'); const card=e.target.closest('.menu-card'); if(pickBtn){ e.stopPropagation(); const m=menus.find(x=>x.name===pickBtn.dataset.pick); pick(m); pickBtn.classList.add('picked'); pickBtn.textContent='기록했어요'; } else if(card) show(menus.find(x=>x.name===card.dataset.name)); });
$('#recommendBtn').onclick=recommend; $('#refreshBtn').onclick=recommend; $('#saveBtn').onclick=()=>pick(current); $('#clearBtn').onclick=()=>{history=[];localStorage.removeItem('lunch-history');renderHistory();}; $('#themeBtn').onclick=()=>document.body.classList.toggle('dark');
renderCategories(); renderCards(); renderHistory(); show(current); loadHistory();
